[workspace]
resolver = "2"

members = ["*/day-*", "aoc"]

[workspace.dependencies]
regex = "1.10.2"
lazy_static = "1.4.0"
aoc = { path = "aoc" }
itertools = "0.12.0"
rayon = "1.8.0"
criterion = {version = "0.5.1"}
rand = "0.8.5"
gcd = "2.3.0"
arrayvec = "0.7.4"